version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ main port
      - "15672:15672"   # RabbitMQ management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Optional: Uncomment below to disable if not needed
    # deploy:
    #   replicas: 0

  api_server:
    build:
      context: .
      dockerfile: docker/api_server.dockerfile
    container_name: api_server
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - .:/app
    command: ["poetry", "run", "python", "run_api.py"]

  worker:
    build:
      context: .
      dockerfile: docker/worker.dockerfile
    container_name: worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - .:/app
    command: ["poetry", "run", "dramatiq", "mxtoai.tasks", "--watch", "./."]

volumes:
  rabbitmq_data:
  ollama_data:
  redis_data:
  