name = "mxgo-email-worker"
main = "src/worker.js"
compatibility_date = "2024-09-23"
workers_dev = true
preview_urls = false
compatibility_flags = [ "set_forwardable_email_full_headers", "nodejs_compat" ]
