from mxtoai.prompts import output_prompts, template_prompts
from mxtoai.schemas import ProcessingInstructions

# default email handles for processing instructions
DEFAULT_EMAIL_HANDLES = [
    ProcessingInstructions(
        handle="summarize",
        aliases=["summarise", "summary"],
        process_attachments=True,
        deep_research_mandatory=False,
        target_model="gpt-4",
        task_template=template_prompts.SUMMARIZE_TEMPLATE,
        output_template=output_prompts.SUMMARIZE_OUTPUT_GUIDELINES,
    ),
    ProcessingInstructions(
        handle="research",
        aliases=["deep-research"],
        process_attachments=True,
        deep_research_mandatory=True,
        add_summary=True,
        target_model="gpt-4",
        task_template=template_prompts.RESEARCH_TEMPLATE,
        output_template=output_prompts.RESEARCH_OUTPUT_GUIDELINES,
    ),
    ProcessingInstructions(
        handle="simplify",
        aliases=["eli5", "explain"],
        process_attachments=True,
        deep_research_mandatory=False,
        target_model="gpt-4",
        task_template=template_prompts.SIMPLIFY_TEMPLATE,
        output_template=output_prompts.SIMPLIFY_OUTPUT_GUIDELINES,
    ),
    ProcessingInstructions(
        handle="ask",
        aliases=["custom", "agent", "assist", "assistant", "hi", "hello", "question"],
        process_attachments=True,
        deep_research_mandatory=False,
        target_model="gpt-4",
        task_template=template_prompts.ASK_TEMPLATE,
        output_template=output_prompts.ASK_OUTPUT_GUIDELINES,
    ),
    ProcessingInstructions(
        handle="fact-check",
        aliases=["factcheck", "verify"],
        process_attachments=True,
        deep_research_mandatory=False,
        target_model="gpt-4",
        task_template=template_prompts.FACT_TEMPLATE,
        output_template=output_prompts.FACT_CHECK_OUTPUT_GUIDELINES,
    ),
    ProcessingInstructions(
        handle="background-research",
        aliases=["background-check", "background"],
        process_attachments=True,
        deep_research_mandatory=False,
        target_model="gpt-4",
        task_template=template_prompts.BACKGROUND_RESEARCH_TEMPLATE,
        output_template=output_prompts.BACKGROUND_OUTPUT_GUIDELINES,
    ),
    ProcessingInstructions(
        handle="translate",
        aliases=["translation"],
        process_attachments=True,
        deep_research_mandatory=False,
        target_model="gpt-4",
        task_template=template_prompts.TRANSLATE_TEMPLATE,
        output_template=output_prompts.TRANSLATION_OUTPUT_GUIDELINES,
    ),
    ProcessingInstructions(
        handle="schedule",
        aliases=["schedule-action"],
        process_attachments=True,
        deep_research_mandatory=False,
        target_model="gpt-4",
        requires_schedule_extraction=True,
        task_template=template_prompts.MEETING_TEMPLATE,
        output_template=output_prompts.MEETING_OUTPUT_GUIDELINES,
    ),
    ProcessingInstructions(
        handle="pdf",
        aliases=["export", "convert", "document", "export-pdf"],
        process_attachments=True,
        deep_research_mandatory=False,
        target_model="gpt-4",
        task_template=template_prompts.PDF_EXPORT_TEMPLATE,
        output_template=output_prompts.PDF_EXPORT_OUTPUT_GUIDELINES,
    ),
    ProcessingInstructions(
        handle="future",
        aliases=[
            "remind",
            "recurring",
            "schedule-task",
            "schedule-reminder",
            "future-task",
            "recurring-task",
            "delayed-processing",
        ],
        process_attachments=True,
        deep_research_mandatory=False,
        target_model="gpt-4",
        task_template=template_prompts.FUTURE_TEMPLATE,
        output_template=output_prompts.FUTURE_OUTPUT_GUIDELINES,
    ),
]
